### ISSUE TITLE
Lời muốn nói! · XOXO :)))

### ISSUE THREAD

**Issue by hunghg255** [hunghg255/hunghg255.github.io#1]
https://hunghg255.github.io/2020/06/02/loi-gioi-thieu/ 

 Xin chào, mình là Hùng. Sau khi học đến năm 3 ngành Điện tử - Viễn thông tại trường Đại học Bách khoa Hà Nội thì mình tự cảm thấy bản thân kém cỏi và

**Comment by hunghg255** [comment]
asdsa

**Comment by hunghg255** [comment]
:D

**Comment by kmacoders** [comment]
hi

**Comment by dungnt11** [comment]
<3

**Comment by hunghg255** [comment]
<3
